language: node_js
node_js: 
  - 13

services:
  - docker

install:
  - echo 'nothing to install'

before_script:
  - echo 'no tests'

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-frontend:local $DOCKER_USERNAME/udagram-frontend:v2
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v2
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v2
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v2

after_sucess:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-frontend:v2
  - docker push $DOCKER_USERNAME/udagram-api-feed:v2
  - docker push $DOCKER_USERNAME/udagram-api-user:v2
  - docker push $DOCKER_USERNAME/reverseproxy:v2