apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: alimbaleo/udagram-api-user:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-db
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: env-db
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: env-db
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: env-db
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-db
              key: JWT_SECRET
        - name: URL
          valueFrom:
            secretKeyRef:
              name: env-db
              key: URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-db-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-db-secret
              key: POSTGRES_HOST